### ISSUE TITLE
feature request - link expiry, removal

### ISSUE THREAD

**Issue by clsferguson** [Shoogn/UrlShortenerServer#3]
probably something i can handle with hangfire, but it would be helping for me at least to have the link expire, then removed either immediately or some time frame later.

thanks for the package

**Comment by Shoogn** [comment]
@clsferguson thanks for opening this feature request, I would like to mention that adding the expire link to your shortener url server it's straightforward and easy all you have to do is to extend the built-in ShortUrlEntity object and add your custom properties to the newly object.
After that you can create a job by using Hangfire to remove the expired URLs.

**Comment by clsferguson** [comment]
Hey thanks, I have done as suggested, I created some custom properties for the UrlsEntity. While I like the idea and i can work with it, I have another suggestion. 

```
            var link = www.test.com/asdlkfjghslkdjfhglkjsdafhglksjdfhglkjsdfhglkjsdfhglkjhsdrf
            var test = new ApplicationShortUrlsEntity
            {
                LongUrl = link,
                Description = "test",
                ExpiryDate = DateTime.Now + TimeSpan.FromDays(1)
            };

            var shortLink = await _urlShortenerManager.CreateAsync(test, cancellationToken);
```

An overload to accept the object like _userManager.CreateAsync(user), not just a string.

**Comment by Shoogn** [comment]
@clsferguson Thanks for replying,  your suggestion is already implemented, but the NuGet package not updated yet, but you can clone the code and see the example and give it a try!

**Comment by Shoogn** [comment]
Hi I would like to open this issue and I am looking forward to discussing the possibility to add the expiration date  and time for the short url.

**Comment by clsferguson** [comment]
I haven't pursued this much since I'm not quite there with the personal project I'm working on. My thought was to add a expiry property, run a check when loading the short link to see if it has expired, then create a reoccurring hangfire task to prune the db periodically.

**Comment by Shoogn** [comment]
@clsferguson, can you write a quick proposal.
